### ISSUE TITLE
getUInt returns invalid values

### ISSUE THREAD

**Issue by mattmook** [goncalossilva/kotlinx-murmurhash#3]
Hi @goncalossilva,

There's currently a bug in `getUInt` when reading values that are negative bytes.

For example, consider the following:

```
val bytes = byteArrayOf(0x2e, 0xf6.toByte())

println(bytes.getUInt(0)) // prints 46
println(bytes.getUInt(1)) // prints 4294967286 but should be 246
```

This looks as simple as just ensuring the value is masked, i.e. `private fun ByteArray.getUInt(index: Int) = get(index).toUInt() and 0xffu` although I've not throughly tested this. I assume the same needs to be applied to `getULong` too.

The test suite is probably not broad enough in terms of the byte values under test; which is why it doesn't pick up this issue. I'm currently in the process of adding an incremental version of murmurhash into my own Multiplatform library, [cryptohash](https://github.com/appmattus/crypto/tree/main/cryptohash) and while looking into that came across this test suite from [Apache Commons Codec](https://github.com/apache/commons-codec/blob/master/src/test/java/org/apache/commons/codec/digest/MurmurHash3Test.java#L397) which helped highlight this issue.

From a testing point of view, with a fix in place, `hash32x86` with a zero seed would be expected to return `0x368f9df1` for the 2-byte array above.

**Comment by goncalossilva** [comment]
Hey @mattmook, good to hear from you!

Good catch, thank you for taking the time. I think an idiomatic way of addressing it is to convert:

```kotlin
private fun ByteArray.getUInt(index: Int) = get(index).toUInt()

private fun ByteArray.getULong(index: Int) = get(index).toULong()
```

into:

```kotlin
private fun ByteArray.getUInt(index: Int) = get(index).toUByte().toUInt()

private fun ByteArray.getULong(index: Int) = get(index).toUByte().toULong()
```

Which behind the scenes does the masking you suggest, but keeps it “Kotlin-esque” by leveraging the expressive conversion methods from/to signed/unsigned that the platform provides.

You're right that the test suite should have caught these. The wordlist is extensive, but it's all "a" to "z", i.e., "\u0041" through "\u005a", which conveniently misses on all of these edge cases. I didn't consider this before, but your Apache Commons Codec share looks like a great resource (good license, too). I'll likely borrow bits of it.

**Comment by goncalossilva** [comment]
Fix coming later today. 😊
