### ISSUE TITLE
Could not resolve com.goncalossilva:murmurhash:0.4.0.

### ISSUE THREAD

**Issue by ziomal601** [goncalossilva/kotlinx-murmurhash#46]
During the build I got this error:

:shared:iosSimulatorArm64Main: Could not resolve com.goncalossilva:murmurhash:0.4.0.
Required by:
    project :shared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Could you please help me?

**Comment by goncalossilva** [comment]
Please share your Gradle configuration, particularly where you list the dependency on this library. Also, is there any other error before this one? Thank you.

**Comment by goncalossilva** [comment]
Closing due to lack of response, but I'd very much like to help debug this in case there is a problem.

The artifact is listed on Maven: https://central.sonatype.com/artifact/com.goncalossilva/murmurhash/0.4.0
